[package]
name = "counter"
version = "0.1.0"
edition = "2023_01"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.6.3"
kill_switch = {git = "https://github.com/starknet-edu/kill-switch.git"}


[[target.starknet-contract]]
casm = true
sierra = true
build-external-contracts = ["kill_switch::KillSwitch"]

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.27.0" }
cairo_test = "2.8.0"

[scripts]
test="snforgeÂ test"